// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQSyQO9Q26EuFFNbSPT8VfKehlC_z_Zvo',
    appId: '1:391974702805:web:ea0f0f20e2c707f9f59c5c',
    messagingSenderId: '391974702805',
    projectId: 'chatapp-38701',
    authDomain: 'chatapp-38701.firebaseapp.com',
    storageBucket: 'chatapp-38701.appspot.com',
    measurementId: 'G-5B5DK81MC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP7_qmi_Pw_fub6VepI8mtSoX1_pdDvDY',
    appId: '1:770536847415:android:0cad43aa0eeb79de1a27b2',
    messagingSenderId: '770536847415',
    projectId: 'chat-app-c1a72',
    storageBucket: 'chat-app-c1a72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoWKYRm8Aqw8BDCRqbbMw2LFZaEsQs-RE',
    appId: '1:770536847415:ios:27648d67c61c85431a27b2',
    messagingSenderId: '770536847415',
    projectId: 'chat-app-c1a72',
    storageBucket: 'chat-app-c1a72.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_fV5TFNavQd261GxE8v5XX693qQLy1zw',
    appId: '1:391974702805:ios:bc8b3229cd5cde6af59c5c',
    messagingSenderId: '391974702805',
    projectId: 'chatapp-38701',
    storageBucket: 'chatapp-38701.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQSyQO9Q26EuFFNbSPT8VfKehlC_z_Zvo',
    appId: '1:391974702805:web:fc2016d447007e7cf59c5c',
    messagingSenderId: '391974702805',
    projectId: 'chatapp-38701',
    authDomain: 'chatapp-38701.firebaseapp.com',
    storageBucket: 'chatapp-38701.appspot.com',
    measurementId: 'G-5ERXNKGDX5',
  );
}